version: '3.8'

volumes:
  mongo_dir:
  mariaDB_dir:
  postgres_dir:
  redis_dir:

networks:
  mongo_net:
  phpmyadmin_net:
  redis_net:
  postgres_net:

services:
  mongodb: 
    container_name: mongo
    image: mongo:4.4.3
    ports:
     - 27017:27017
    volumes:
     - mongo_dir:/data/db
    networks:
     - mongo_net
    environment:
     - MONGODB_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
     - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
     - mongo_net
    depends_on:
     - mongodb

  mariaDB:
    image: mariadb:10.6 
    ports:
     - 3307:3307
    volumes:
     - mariaDB_dir:/data/db
    networks:
     - phpmyadmin_net
    environment:
     - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
     - mariaDB
    ports:
     - 8080:80
    networks:
     - phpmyadmin_net
    environment:
     - PMA_HOST=mariaDB

  postgres: 
    image: postgres:14.0
    ports:
     - 5432:5432
    volumes:
     - postgres_dir:/vol/postgresql/data
    networks:
     - postgres_net
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}

  pgadmin-compose:
    image: fenglc/pgadmin4:latest
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
     - 5050:5050
    networks:
     - postgres_net
    depends_on:
     - postgres

  redis:
    image: redis:6.2.6
    command: ["redis-server", "--appendonly", "yes"]
    ports:
     - 6379:6379
    networks:
     - redis_net
    links: 
     - redis-commander
    volumes:
     - redis_dir:/data/db

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
     - REDIS_HOSTS=redis
     - REDIS_PORT=redis:6379
     - REDIS_PASSWORD=root
     - HTTP_USER=root
     - HTTP_PASSWORD=root
    ports:
     - 8082:8082
    networks:
     - redis_net

